[package]
name = "kernel-sync"
version = "0.1.0"
edition = "2021"

[dependencies]
cfg-if = "1.0"
spin = "0.9"

id-alloc = { path = "../id-alloc" }

[target.'cfg(target_arch = "riscv64")'.dependencies]
riscv = "0.10"