[package]
name = "tcore-kernel"
version = "0.1.0"
edition = "2021"
authors = ["TKF <kaifu6821@qq.com>"]

[dependencies]
log = "0.4"
riscv = "0.9"
sbi-rt = { git = "https://github.com/rustsbi/sbi-rt", branch = "main" }
