[package]
name = "tmm_rv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
bitflags = "1.3.2"
buddy_system_allocator = "0.8"
riscv = "0.9"
spin = "0.9"
tmm_addr = { path = "../tmm_addr" }